export const cartTypes = {
  // Sync
  CHANGE_STATE_CART: 'cart/CHANGE_STATE_CART',
  CHANGE_CART_SUCCESS: 'cart/CHANGE_CART_SUCCESS',

  FETCH_PRODUCTS_REQUEST: 'cart/FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'cart/FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'cart/FETCH_PRODUCTS_FAILURE',

  FETCH_PRODUCTS_OPTIONS_REQUEST: 'cart/FETCH_PRODUCTS_OPTIONS_REQUEST',
  FETCH_PRODUCTS_OPTIONS_SUCCESS: 'cart/FETCH_PRODUCTS_OPTIONS_SUCCESS',
  FETCH_PRODUCTS_OPTIONS_FAILURE: 'cart/FETCH_PRODUCTS_OPTIONS_FAILURE',

  // async
  FETCH_PRODUCTS_ASYNC: 'cart/FETCH_PRODUCTS_ASYNC',
  FETCH_PRODUCTS_OPTIONS_ASYNC: 'cart/FETCH_PRODUCTS_OPTIONS_ASYNC',
};
