export const accountTypes = {
  // Sync
  FETCH_ACCOUNT_REQUEST: 'account/FETCH_ACCOUNT_REQUEST',
  FETCH_ACCOUNT_SUCCESS: 'account/FETCH_ACCOUNT_SUCCESS',
  FETCH_ACCOUNT_FAILURE: 'account/FETCH_ACCOUNT_FAILURE',
  LOGOUT_ACCOUNT: 'account/LOGOUT_ACCOUNT',

  // Async
  FETCH_ACCOUNT_ASYNC: 'account/FETCH_ACCOUNT_ASYNC',
};
